# Site Settings
title: Kobe Cho 개발자 블로그
email: eotlr720@naver.com
description: 잡다한 지식 아카이빙용
baseurl: ""
url: "https://kobejo.github.io" # the base hostname & protocol for your site
google_analytics: # "UA-XXXXXXXX-X"
locale: ko-KR

# User Settings
username: Daesik Cho
user_description: Software Developer
disqus_username: Kobe

# Social Media
# Remove the item if you don't need it
github_username: KobeJo
instagram_username: jodaesik

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']